HTTP_SERVER_ADDRESS: 0.0.0.0:9002

ACCESS_TOKEN_EXPIRES_IN_AS_SECONDS: 3600
REFRESH_TOKEN_EXPIRES_IN_AS_SECONDS: 86400
ID_TOKEN_EXPIRES_IN_AS_SECONDS: 86400

ROOT_ACCOUNT_EMAIL: admin@email.com

DATABASE_MAX_OPEN_CONNECTIONS: 5
DATABASE_MAX_IDLE_CONNECTIONS: 5
DATABASE_CONNECTION_MAX_LIFETIME_IN_SECONDS: 3600 # 1 hour
DATABASE_CONNECTION_MAX_IDLE_TIME_IN_SECONDS: 3600 # 1 hour
